baseURL = "http://example.org/"
languageCode = "en-us"
title = "lregueiro.dev"
theme= "rocinante"

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.ico"
  mainSections = ["posts"]
  email = "mail@example.com"
  about = """
Hi. I'm **Leandro**, my friends also know me as **Leo**.
"""

  [[params.links]]
    [[params.links.link]]
      name = "Resume"
      href = "/Resume.pdf"
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true
  [[params.links.link]]
        name = "Github"
        href = "https://github.com/lregueiro"
        new_tab = true

