baseURL = "http://lregueiro.github.io"
languageCode = "en-us"
title = "lregueiro.dev"
theme= "clean"

[params]
  ProjectTitle = "lregueiro.dev"
  ProjectSubtitle = "About programming and short sentences"
  AuthorName = "Leandro Regueiro"
  Favicon = "/icons/favicon.ico"
  Email = "mail@example.com"
  GithubUser = "lregueiro"
  ExcludeCredits = false
  ExcludeMediaOnSummary = false

#  [menu]
#      [[menu.main]]
#          name = "Home"
#          url = "/"
#          weight = 1
#        [[menu.main]]
#          name = "Posts"
#          url = "/post/"
#          weight = 2
#        [[menu.main]]
#          name = "Tags"
#          url = "/tags/"
#          weight = 3



